---
deployment:
  tasks:
    - export DEPLOYPATH=/home/gorn2792/public_html/
    # Sinkronisasi file kecuali folder yang dikecualikan
    - rsync -av --exclude='.git/' --exclude='vendor/' --exclude='storage/' --exclude='node_modules/' ./ $DEPLOYPATH
